// Code generated by type-generator-tool. DO NOT EDIT.

package types

import (
	"database/sql/driver"
	"fmt"
	"strconv"
	"github.com/google/uuid"
)

type ChatID struct {
	value any	
}

var ChatIDNil = ChatID{value: nil}

// Type returns the type name as string for Entgo compatibility
func (ChatID) Type() string {
	return "ChatID"
}

func NewChatID() *ChatID {
	return &ChatID{}
}

func (c *ChatID) MarshalText() ([]byte, error) {
	if strValue, ok := c.value.(string); ok {
		return []byte(strValue), nil
	}
	return nil, fmt.Errorf("invalid type for ChatID: %T", c.value)
}

func (c *ChatID) IsZero() bool {
	return c.value == nil
}

func (c *ChatID) UnmarshalText(text []byte) error {
	c.value = string(text)
	return nil
}

func (c *ChatID) Value() (driver.Value, error) {
	switch v := c.value.(type) {
	case nil:
		*c = ChatIDNil
        return uuid.Nil.String(), nil
	case uuid.UUID:
		return v.String(), nil
	case string:
		return v, nil
	case []byte:
		if len(v) == 0 {
			return uuid.Nil.String(), nil
		}
		return string(v), nil
	case int:
		return strconv.Itoa(v), nil
	default:
		return nil, fmt.Errorf("unsupported type: %s", v)
	}
}

func (c *ChatID) Scan(value any) error {
	switch v := value.(type) {
	case nil:
		*c = ChatIDNil
        return nil
	case string:
		val, err := uuid.Parse(v)
		if err != nil {
			*c = ChatID{value: v}
		}
		*c = ChatID{value: val}
		return nil
	case []byte:
		*c = ChatID{value: v}
		return nil
	case int:
		*c = ChatID{value: strconv.Itoa(v)}
		return nil
	default:
		return fmt.Errorf("unsupported type: %T", v)
	}
}

func (c *ChatID) Validate() error {
	if c.IsZero() {
		return fmt.Errorf("ChatID is zero value")
	}

	switch v := c.value.(type) {
	case uuid.UUID:
		return nil 
	case string:
		if _, err := uuid.Parse(v); err != nil {
			return fmt.Errorf("invalid string format for ChatID: %s", v)
		}
		return nil
	case []byte:
		strValue := string(v)
		if _, err := uuid.Parse(strValue); err != nil {
			return fmt.Errorf("invalid byte format for ChatID: %s", strValue)
		}
		return nil
	case int:
		return fmt.Errorf("int type is not valid for ChatID")
	default:
		return fmt.Errorf("unsupported type: %T", v)
	}
}

func (c *ChatID) String() string {
	switch v := c.value.(type) {
	case uuid.UUID:
		return v.String() 
	case string:
		return v
	case []byte:
		if len(v) == 0 {
			return uuid.Nil.String()
		}
		return string(v)
	case int:
		return strconv.Itoa(v)
	default:
		return uuid.Nil.String()
	}
}

func (c *ChatID) Matches(x interface{}) bool {
	switch v := x.(type) {
	case string:
		return c.value == v
	case []byte:
		return c.value == string(v)
	case int:
		if intValue, ok := c.value.(int); ok {
			return intValue == v
		}
		return false
	default:
		return false
	}
}

func Parse[T any](input any) (*ChatID, error) {
	if input == "" {
		return &ChatID{}, fmt.Errorf("input cannot be empty")
	}
	return &ChatID{value: input}, nil
}

func MustParse[T any](input any) *ChatID {
	val, err := Parse[T](input)
	if err != nil {
		panic(err)
	}
	return val
}

