// Code generated by type-generator-tool. DO NOT EDIT.

package types

import (
	"database/sql/driver"
	"fmt"
	"strconv"
	"github.com/google/uuid"
)

type ProblemID struct {
	value any	
}

var ProblemIDNil = ProblemID{value: nil}

// Type returns the type name as string for Entgo compatibility
func (ProblemID) Type() string {
	return "ProblemID"
}

func NewProblemID() *ProblemID {
	return &ProblemID{}
}

func (c *ProblemID) MarshalText() ([]byte, error) {
	if c.value == nil {
		return []byte(uuid.Nil.String()), nil
	}	
	switch v := c.value.(type) {
	case uuid.UUID:
		return []byte(v.String()), nil
	case string:
		return []byte(v), nil
	case []byte:
		return v, nil
	default:
		return nil, fmt.Errorf("invalid type for ProblemID: %T", c.value)
	}
}

func (c *ProblemID) IsZero() bool {
	return c.value == nil
}

func (c *ProblemID) UnmarshalText(text []byte) error {
	c.value = string(text)
	return nil
}

func (c *ProblemID) Value() (driver.Value, error) {
	switch v := c.value.(type) {
	case nil:
		*c = ProblemIDNil
        return uuid.Nil.String(), nil
	case uuid.UUID:
		return v.String(), nil
	case string:
		return v, nil
	case []byte:
		if len(v) == 0 {
			return uuid.Nil.String(), nil
		}
		return string(v), nil
	case int:
		return strconv.Itoa(v), nil
	default:
		return nil, fmt.Errorf("unsupported type: %s", v)
	}
}

func (c *ProblemID) Scan(value any) error {
	switch v := value.(type) {
	case nil:
		*c = ProblemIDNil
        return nil
	case string:
		val, err := uuid.Parse(v)
		if err != nil {
			*c = ProblemID{value: v}
		}
		*c = ProblemID{value: val}
		return nil
	case []byte:
		*c = ProblemID{value: v}
		return nil
	case int:
		*c = ProblemID{value: strconv.Itoa(v)}
		return nil
	default:
		return fmt.Errorf("unsupported type: %T", v)
	}
}

func (c *ProblemID) Validate() error {
	if c.IsZero() {
		return fmt.Errorf("ProblemID is zero value")
	}

	switch v := c.value.(type) {
	case uuid.UUID:
		return nil 
	case string:
		if _, err := uuid.Parse(v); err != nil {
			return fmt.Errorf("invalid string format for ProblemID: %s", v)
		}
		return nil
	case []byte:
		strValue := string(v)
		if _, err := uuid.Parse(strValue); err != nil {
			return fmt.Errorf("invalid byte format for ProblemID: %s", strValue)
		}
		return nil
	case int:
		return fmt.Errorf("int type is not valid for ProblemID")
	default:
		return fmt.Errorf("unsupported type: %T", v)
	}
}

func (c *ProblemID) String() string {
	switch v := c.value.(type) {
	case uuid.UUID:
		return v.String() 
	case string:
		return v
	case []byte:
		if len(v) == 0 {
			return uuid.Nil.String()
		}
		return string(v)
	case int:
		return strconv.Itoa(v)
	default:
		return uuid.Nil.String()
	}
}

func (c *ProblemID) Matches(x interface{}) bool {
	if c == nil {
		return false
	}
	
	switch v := x.(type) {
	case string:
		return c.String() == v
	case []byte:
		return c.String() == string(v)
	case uuid.UUID:
		if uuidVal, ok := c.value.(uuid.UUID); ok {
			return uuidVal == v
		}
		return false
	case *ProblemID:
		if v == nil {
			return false
		}
		return c.String() == v.String()
	case ProblemID:
		return c.String() == v.String()
	default:
		return false
	}
}

func ParseProblemID(input any) (*ProblemID, error) {
	if input == nil {
		return &ProblemIDNil, nil
	}
	
	switch v := input.(type) {
	case string:
		if v == "" {
			return &ProblemIDNil, nil
		}
		if id, err := uuid.Parse(v); err == nil {
			return &ProblemID{value: id}, nil
		}
		return &ProblemID{value: v}, nil
	case uuid.UUID:
		return &ProblemID{value: v}, nil
	case []byte:
		if len(v) == 0 {
			return &ProblemIDNil, nil
		}
		if id, err := uuid.Parse(string(v)); err == nil {
			return &ProblemID{value: id}, nil
		}
		return &ProblemID{value: string(v)}, nil
	case *ProblemID:
		if v == nil {
			return &ProblemIDNil, nil
		}
		return v, nil
	case ProblemID:
		return &v, nil
	default:
		return nil, fmt.Errorf("unsupported type for ProblemID: %T", input)
	}
}

func MustParseProblemID(input any) *ProblemID {
	val, err := ParseProblemID(input)
	if err != nil {
		panic(err)
	}
	return val
}

