// Code generated by type-generator-tool. DO NOT EDIT.

package types

import (
	"database/sql/driver"
	"fmt"
	"strconv"
	"github.com/google/uuid"
)

type MessageID struct {
	value any	
}

var MessageIDNil = MessageID{value: nil}

// Type returns the type name as string for Entgo compatibility
func (MessageID) Type() string {
	return "MessageID"
}

func NewMessageID() *MessageID {
	return &MessageID{}
}

func (c *MessageID) MarshalText() ([]byte, error) {
	if c.value == nil {
		return []byte(uuid.Nil.String()), nil
	}	
	switch v := c.value.(type) {
	case uuid.UUID:
		return []byte(v.String()), nil
	case string:
		return []byte(v), nil
	case []byte:
		return v, nil
	default:
		return nil, fmt.Errorf("invalid type for MessageID: %T", c.value)
	}
}

func (c *MessageID) IsZero() bool {
	return c.value == nil
}

func (c *MessageID) UnmarshalText(text []byte) error {
	c.value = string(text)
	return nil
}

func (c *MessageID) Value() (driver.Value, error) {
	switch v := c.value.(type) {
	case nil:
		*c = MessageIDNil
        return uuid.Nil.String(), nil
	case uuid.UUID:
		return v.String(), nil
	case string:
		return v, nil
	case []byte:
		if len(v) == 0 {
			return uuid.Nil.String(), nil
		}
		return string(v), nil
	case int:
		return strconv.Itoa(v), nil
	default:
		return nil, fmt.Errorf("unsupported type: %s", v)
	}
}

func (c *MessageID) Scan(value any) error {
	switch v := value.(type) {
	case nil:
		*c = MessageIDNil
        return nil
	case string:
		val, err := uuid.Parse(v)
		if err != nil {
			*c = MessageID{value: v}
		}
		*c = MessageID{value: val}
		return nil
	case []byte:
		*c = MessageID{value: v}
		return nil
	case int:
		*c = MessageID{value: strconv.Itoa(v)}
		return nil
	default:
		return fmt.Errorf("unsupported type: %T", v)
	}
}

func (c *MessageID) Validate() error {
	if c.IsZero() {
		return fmt.Errorf("MessageID is zero value")
	}

	switch v := c.value.(type) {
	case uuid.UUID:
		return nil 
	case string:
		if _, err := uuid.Parse(v); err != nil {
			return fmt.Errorf("invalid string format for MessageID: %s", v)
		}
		return nil
	case []byte:
		strValue := string(v)
		if _, err := uuid.Parse(strValue); err != nil {
			return fmt.Errorf("invalid byte format for MessageID: %s", strValue)
		}
		return nil
	case int:
		return fmt.Errorf("int type is not valid for MessageID")
	default:
		return fmt.Errorf("unsupported type: %T", v)
	}
}

func (c *MessageID) String() string {
	switch v := c.value.(type) {
	case uuid.UUID:
		return v.String() 
	case string:
		return v
	case []byte:
		if len(v) == 0 {
			return uuid.Nil.String()
		}
		return string(v)
	case int:
		return strconv.Itoa(v)
	default:
		return uuid.Nil.String()
	}
}

func (c *MessageID) Matches(x interface{}) bool {
	if c == nil {
		return false
	}
	
	switch v := x.(type) {
	case string:
		return c.String() == v
	case []byte:
		return c.String() == string(v)
	case uuid.UUID:
		if uuidVal, ok := c.value.(uuid.UUID); ok {
			return uuidVal == v
		}
		return false
	case *MessageID:
		if v == nil {
			return false
		}
		return c.String() == v.String()
	case MessageID:
		return c.String() == v.String()
	default:
		return false
	}
}

func ParseMessageID(input any) (*MessageID, error) {
	if input == nil {
		return &MessageIDNil, nil
	}
	
	switch v := input.(type) {
	case string:
		if v == "" {
			return &MessageIDNil, nil
		}
		if id, err := uuid.Parse(v); err == nil {
			return &MessageID{value: id}, nil
		}
		return &MessageID{value: v}, nil
	case uuid.UUID:
		return &MessageID{value: v}, nil
	case []byte:
		if len(v) == 0 {
			return &MessageIDNil, nil
		}
		if id, err := uuid.Parse(string(v)); err == nil {
			return &MessageID{value: id}, nil
		}
		return &MessageID{value: string(v)}, nil
	case *MessageID:
		if v == nil {
			return &MessageIDNil, nil
		}
		return v, nil
	case MessageID:
		return &v, nil
	default:
		return nil, fmt.Errorf("unsupported type for MessageID: %T", input)
	}
}

func MustParseMessageID(input any) *MessageID {
	val, err := ParseMessageID(input)
	if err != nil {
		panic(err)
	}
	return val
}

