// Package pkg provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package pkg

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xW32/bNhD+V4jbHjaAsuTGBQoBfWiStc2wDsGSYgWyPNDSxWInkSpJuU4D/e/DUdQP",
	"x0pbDF26Fyfikby77777eHeQ6arWCpWzkN5BLYyo0KHxX+/+wA8NWnd2+hpFjobWpIIUiu6TgxIVQgrv",
	"orAzOjsFDgY/NNJgDqkzDXKwWYGVoNM32lTCQQpNI3Pg4G5rOm+dkWoDHHbRRkeyqrVxXTiugBQ20hXN",
	"epHpKs5Vjttot4s3OlJSvRdRVggXS+XQKFHGdKGFNtwUrveLiyEZaNu2D8rn+Ysx2idXG12jcRL9cqZz",
	"pL8/GryBFH6IR6zicDr2R09oY8shRydk6c/uJ9ZyqNBascEZWzsF7GrYyDv/1y2H0Ul6BznazMjaSU2V",
	"yLRyQirLXl9enjOkjYzOWSZUzmyNmbyRGVs3Viq0lpV6I7O9fT+5AlkprGNVYx1bI/urSZIjfM6WSZL8",
	"vAAOqJoK0qtVkvBVsuSr5IivkhV/miSc9tDPkn6e0M8R/ayuOVRSyYoO0rk+aSrUxlNnF9G10VYYIpGl",
	"1Ic8j0UeqgWT7N8q0bhCG/kJ8+n6S23WMs9RTRd/1+6lbtTexrPAkgs0WzRd1SfmE4PC4Ukh3IHpbZ0/",
	"ZDrFEh8wvelK2YfS2amgr9C9ltZpc9uneUi+xtiOlAdUqsUGL+Qnz4ZK7DqQlwTyAPnyEHHiWVjS6/eY",
	"ObgXiK21sngYSS6c+FIbhEztOTH3PqP9BZT2m7EH9l10dT3L5yTi32rAA+KyJwlvLRqvWINpEB/VlGXL",
	"Ya3z28OuuyyQUeehckzfMOqg0LaLA78th8wTK3/hZm6SFVonqpp9LFBNb2IfhWXhJN064EJMjJyscM6V",
	"fHQMQ1E/B+M9PviQhpIHjKcoTbgyPjyzjDn93o9KYND9In9dsaoBuu+cxVjDWZXY6+6DUoQs/P/SYWW/",
	"UixgdCWMEbf+WztRnuhGzbUK2ZhqqjUa6rreLxNbIUuxLqfNN1W9mdfVU3v0RYS7QJWHyB4U5XD6OIhC",
	"JXa/odpQIVZJ0N9+YTlXQS1qGdGzu0EV4c4ZETmx8VdvRSmJLJAO8fJKqudLXondc7q+G1tmkvHhXM/U",
	"bS+lbyDvoRlbDthPTF+cjShqmrYwa4x0txdk6xyvURg0LxpCq/962TfBr39eQpjRKKfOOpa3cK7u8JDq",
	"RvtXUrqSLMdC/c0umpr6hNGrzE5KSTr94vwMOGzR2I5O2yUlomtUopaQwtEiWRwFrfTxxZvhcfSoaTtD",
	"ylfoGLUZK7qdREFCV5CdHjQ419aNz6x3MM7YV/MIjlvigxm8ve5IgNb1PAxPkdfFui5l5r3H7y2FeDcZ",
	"vz9XrcOZ5B7faJb3Cx2TPEZPkuQ/CSCQ1UewD3ivRayU1i2ohKtvGMNA2ftuj0XOBlw4PH0Mn/24yrp5",
	"lU37KbZjbz/MThIApvDjMFM47UcMYuw8UyeS8f+l6oxUPzJX55T1YbKOY1y7r4Ye1akOXl0TZtbXu8N8",
	"/8JT3GKp64oErdsFHBpTBklM47jUmSgLbV36LHmWxKRy1+0/AQAA//8vjDE45w8AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
