// Package pkg provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package pkg

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RVTU/bQBD9K6tpj04cygX5BkSFVKqECqhIKIeNPYmXej/YHQdS5P9ezdqJHRK1lare",
	"4t3ZmTfvzZu8QW61swYNBcjewEkvNRL6+PXwDZ9rDDSbXqMs0PNZgSH3ypGyBjK4N+q5RqEKNKSWCr1Y",
	"Wi+oROHbp2NIQHFk2WZIwEiNkMHDqEs+mk0hAQ5XHgvIyNeYQMhL1JILLq3XkiCDulYFJEAbx+8DeWVW",
	"0DTNNjhCvkK6VoGs33TpY1feOvSkMIbktQ829vIuVQJOrvBW/US+1PJV6VpDdjKZJKCV2X7tIChDuEIP",
	"DKE7sosnzIlTDYEEZ03AQySFpNjiR49LyOBD2ouRdj2lXzEEucJwI1cYK/VMPbYJ5k0CXdRhCVlTaf2s",
	"+DOTCbyOVnbUHXLI+P5+NuVeFrbYHGp/V6LIrSE0JOwyiq5bGONDmRLIPUrC4pyOZFIaA0ntxEuJZphJ",
	"vMggupecdddCIQlHpDQeK6X+pd13FMenOxY7LobdDOhvRTrQoOsl/laEOvyl5tDPlfRebuK3JVld2toc",
	"o5HvhKn1Aj0rsq0r5FqqSi6qoTDD4R32uwO7V2sebYZ57RVtbhlm284CpUd/XlPZf33e8v7l+x105uSK",
	"7W2PoCRyrX+VWdroR0UV31xI80Pc1s5ZT+KylCQuK8Vjdn4zgwTW6EPb8fqEObEOjXQKMjgdT8anwD6m",
	"MuJLVzsbRl1sOMLbFZLIuUrZRjJLrJ/ke7YO3NhAvaFjgX5PPh4Xsw9JD/ZoM29Jx0AXnbc6J0XPOlep",
	"PFZPnwJDfBvsw98NzuH2a/b15eUaD9qVFDn6NJn8FwDd1osI9gnf2kVUiv8hmqYZjldkdDhYj3PmK6Bf",
	"b/neTzfFNVbWaZ6QNgoSqH3VzViWppXNZVXaQNnZ5GyS8tjMm18BAAD//5h+Onr8BgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
