// Package pkg provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package pkg

import (
	"time"

	"github.com/dndev-xx/go-ninja-chat/internal/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ErrorCode.
const (
	ErrorCodeBadRequest           ErrorCode = 400
	ErrorCodeCreateChatError      ErrorCode = 1000
	ErrorCodeDeleteChatError      ErrorCode = 1002
	ErrorCodeForbidden            ErrorCode = 403
	ErrorCodeInternalServerError  ErrorCode = 500
	ErrorCodeMessageNotFoundError ErrorCode = 1003
	ErrorCodeNotFound             ErrorCode = 404
	ErrorCodeUnauthorized         ErrorCode = 401
	ErrorCodeUpdateChatError      ErrorCode = 1001
	N1004                         ErrorCode = 1004
)

// Error defines model for Error.
type Error struct {
	// Code contains HTTP error codes and specific business logic error codes (the last must be >= 1000).
	Code    ErrorCode `json:"code"`
	Details *string   `json:"details,omitempty"`
	Message string    `json:"message"`
}

// ErrorCode contains HTTP error codes and specific business logic error codes (the last must be >= 1000).
type ErrorCode int

// GetHistoryRequest defines model for GetHistoryRequest.
type GetHistoryRequest struct {
	Cursor   *string `json:"cursor,omitempty"`
	PageSize *int    `json:"pageSize,omitempty"`
}

// GetHistoryResponse defines model for GetHistoryResponse.
type GetHistoryResponse struct {
	Data MessagesPage `json:"data"`
}

// Message defines model for Message.
type Message struct {
	AuthorId types.UserID `json:"authorId"`

	// Body The content of the message.
	Body string `json:"body"`

	// CreatedAt Timestamp when the message was created.
	CreatedAt time.Time       `json:"createdAt"`
	Id        types.MessageID `json:"id"`
}

// MessageHeader defines model for MessageHeader.
type MessageHeader struct {
	AuthorID  *types.UserID    `json:"authorID,omitempty"`
	CreatedAt *time.Time       `json:"createdAt,omitempty"`
	MessageID *types.MessageID `json:"messageID,omitempty"`
}

// MessagesPage defines model for MessagesPage.
type MessagesPage struct {
	Messages []Message `json:"messages"`

	// TotalCount Total number of messages available.
	TotalCount int `json:"totalCount"`
}

// SendMessageRequest defines model for SendMessageRequest.
type SendMessageRequest struct {
	MessageBody string `json:"messageBody" validate:"required,min=1,max=4000"`
}

// SendMessageResponse defines model for SendMessageResponse.
type SendMessageResponse struct {
	Data  *MessageHeader `json:"data,omitempty"`
	Error *Error         `json:"error,omitempty"`
}

// XRequestIDHeader defines model for XRequestIDHeader.
type XRequestIDHeader = types.RequestID

// PostV1GetHistoryParams defines parameters for PostV1GetHistory.
type PostV1GetHistoryParams struct {
	XRequestID XRequestIDHeader `json:"X-Request-ID"`
}

// PostV1SendMessageParams defines parameters for PostV1SendMessage.
type PostV1SendMessageParams struct {
	XRequestID XRequestIDHeader `json:"X-Request-ID"`
}

// PostV1GetHistoryJSONRequestBody defines body for PostV1GetHistory for application/json ContentType.
type PostV1GetHistoryJSONRequestBody = GetHistoryRequest

// PostV1SendMessageJSONRequestBody defines body for PostV1SendMessage for application/json ContentType.
type PostV1SendMessageJSONRequestBody = SendMessageRequest
