// Code generated by options-gen v0.54.0. DO NOT EDIT.

package websocketstream

import (
	fmt461e464ebed9 "fmt"
	"time"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
	"go.uber.org/zap"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	logger *zap.Logger,
	upgrader Upgrader,
	shutdownCh <-chan struct{},
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	o.pingPeriod, _ = time.ParseDuration("3s")

	o.logger = logger
	o.upgrader = upgrader
	o.shutdownCh = shutdownCh

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithPingPeriod(opt time.Duration) OptOptionsSetter {
	return func(o *Options) { o.pingPeriod = opt }
}

func WithEventStream(opt eventStream) OptOptionsSetter {
	return func(o *Options) { o.eventStream = opt }
}

func WithEventPublisher(opt eventPublisher) OptOptionsSetter {
	return func(o *Options) { o.eventPublisher = opt }
}

func WithEventAdapter(opt EventAdapter) OptOptionsSetter {
	return func(o *Options) { o.eventAdapter = opt }
}

func WithEventWriter(opt EventWriter) OptOptionsSetter {
	return func(o *Options) { o.eventWriter = opt }
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("pingPeriod", _validate_Options_pingPeriod(o)))
	errs.Add(errors461e464ebed9.NewValidationError("logger", _validate_Options_logger(o)))
	errs.Add(errors461e464ebed9.NewValidationError("upgrader", _validate_Options_upgrader(o)))
	errs.Add(errors461e464ebed9.NewValidationError("shutdownCh", _validate_Options_shutdownCh(o)))
	return errs.AsError()
}

func _validate_Options_pingPeriod(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.pingPeriod, "omitempty,min=100ms,max=30s"); err != nil {
		return fmt461e464ebed9.Errorf("field `pingPeriod` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_logger(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.logger, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `logger` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_upgrader(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.upgrader, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `upgrader` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_shutdownCh(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.shutdownCh, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `shutdownCh` did not pass the test: %w", err)
	}
	return nil
}
