// Code generated by options-gen. DO NOT EDIT.

package serverclient

import (
	fmt461e464ebed9 "fmt"

	mw "github.com/dndev-xx/go-ninja-chat/internal/middlewares"
	clientv1 "github.com/dndev-xx/go-ninja-chat/internal/server-client/v1/pkg"
	wsv1 "github.com/dndev-xx/go-ninja-chat/internal/server-event/v1/pkg"
	"github.com/getkin/kin-openapi/openapi3"
	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
	"github.com/labstack/echo/v4"
	"go.uber.org/zap"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	logger *zap.Logger,
	addr string,
	allowOrigins []string,
	v1Swagger *openapi3.T,
	v1Handlers clientv1.ServerInterface,
	v1WsHandler wsv1.ServerInterface,
	keycloakClient mw.Introspector,
	resource string,
	role string,
	errorHandler echo.HTTPErrorHandler,
	secWsProtocols string,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	o.logger = logger

	o.addr = addr

	o.allowOrigins = allowOrigins

	o.v1Swagger = v1Swagger

	o.v1Handlers = v1Handlers

	o.v1WsHandler = v1WsHandler

	o.keycloakClient = keycloakClient

	o.resource = resource

	o.role = role

	o.errorHandler = errorHandler

	o.secWsProtocols = secWsProtocols

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("addr", _validate_Options_addr(o)))
	return errs.AsError()
}

func _validate_Options_addr(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.addr, "hostname_port"); err != nil {
		return fmt461e464ebed9.Errorf("field `addr` did not pass the test: %w", err)
	}
	return nil
}
