package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"text/template"
)

const header = "// Code generated by type-generator-tool. DO NOT EDIT.\n"

var temp = template.Must(
	template.New("typegen").Parse(
		header + `
package {{.Package}}

import (
	{{- range .Import}}
	"{{.}}"
	{{- end}}
)

type {{.Type}} struct {
	value any	
}

var {{.Type}}Nil = {{.Type}}{value: nil}

// Type returns the type name as string for Entgo compatibility
func ({{.Type}}) Type() string {
	return "{{.Type}}"
}

func New{{.Type}}() *{{.Type}} {
	return &{{.Type}}{}
}

func (c *{{.Type}}) MarshalText() ([]byte, error) {
	if c.value == nil {
		return []byte(uuid.Nil.String()), nil
	}	
	switch v := c.value.(type) {
	case uuid.UUID:
		return []byte(v.String()), nil
	case string:
		return []byte(v), nil
	case []byte:
		return v, nil
	default:
		return nil, fmt.Errorf("invalid type for {{.Type}}: %T", c.value)
	}
}

func (c *{{.Type}}) IsZero() bool {
	return c.value == nil
}

func (c *{{.Type}}) UnmarshalText(text []byte) error {
	c.value = string(text)
	return nil
}

func (c *{{.Type}}) Value() (driver.Value, error) {
	switch v := c.value.(type) {
	case nil:
		*c = {{.Type}}Nil
        return uuid.Nil.String(), nil
	case uuid.UUID:
		return v.String(), nil
	case string:
		return v, nil
	case []byte:
		if len(v) == 0 {
			return uuid.Nil.String(), nil
		}
		return string(v), nil
	case int:
		return strconv.Itoa(v), nil
	default:
		return nil, fmt.Errorf("unsupported type: %s", v)
	}
}

func (c *{{.Type}}) Scan(value any) error {
	switch v := value.(type) {
	case nil:
		*c = {{.Type}}Nil
        return nil
	case string:
		val, err := uuid.Parse(v)
		if err != nil {
			*c = {{.Type}}{value: v}
		}
		*c = {{.Type}}{value: val}
		return nil
	case []byte:
		*c = {{.Type}}{value: v}
		return nil
	case int:
		*c = {{.Type}}{value: strconv.Itoa(v)}
		return nil
	default:
		return fmt.Errorf("unsupported type: %T", v)
	}
}

func (c *{{.Type}}) Validate() error {
	if c.IsZero() {
		return fmt.Errorf("{{.Type}} is zero value")
	}

	switch v := c.value.(type) {
	case uuid.UUID:
		return nil 
	case string:
		if _, err := uuid.Parse(v); err != nil {
			return fmt.Errorf("invalid string format for {{.Type}}: %s", v)
		}
		return nil
	case []byte:
		strValue := string(v)
		if _, err := uuid.Parse(strValue); err != nil {
			return fmt.Errorf("invalid byte format for {{.Type}}: %s", strValue)
		}
		return nil
	case int:
		return fmt.Errorf("int type is not valid for {{.Type}}")
	default:
		return fmt.Errorf("unsupported type: %T", v)
	}
}

func (c *{{.Type}}) String() string {
	switch v := c.value.(type) {
	case uuid.UUID:
		return v.String() 
	case string:
		return v
	case []byte:
		if len(v) == 0 {
			return uuid.Nil.String()
		}
		return string(v)
	case int:
		return strconv.Itoa(v)
	default:
		return uuid.Nil.String()
	}
}

func (c *{{.Type}}) Matches(x interface{}) bool {
	if c == nil {
		return false
	}
	
	switch v := x.(type) {
	case string:
		return c.String() == v
	case []byte:
		return c.String() == string(v)
	case uuid.UUID:
		if uuidVal, ok := c.value.(uuid.UUID); ok {
			return uuidVal == v
		}
		return false
	case *{{.Type}}:
		if v == nil {
			return false
		}
		return c.String() == v.String()
	case {{.Type}}:
		return c.String() == v.String()
	default:
		return false
	}
}

func Parse{{.Type}}(input any) (*{{.Type}}, error) {
	if input == nil {
		return &{{.Type}}Nil, nil
	}
	
	switch v := input.(type) {
	case string:
		if v == "" {
			return &{{.Type}}Nil, nil
		}
		if id, err := uuid.Parse(v); err == nil {
			return &{{.Type}}{value: id}, nil
		}
		return &{{.Type}}{value: v}, nil
	case uuid.UUID:
		return &{{.Type}}{value: v}, nil
	case []byte:
		if len(v) == 0 {
			return &{{.Type}}Nil, nil
		}
		if id, err := uuid.Parse(string(v)); err == nil {
			return &{{.Type}}{value: id}, nil
		}
		return &{{.Type}}{value: string(v)}, nil
	case *{{.Type}}:
		if v == nil {
			return &{{.Type}}Nil, nil
		}
		return v, nil
	case {{.Type}}:
		return &v, nil
	default:
		return nil, fmt.Errorf("unsupported type for {{.Type}}: %T", input)
	}
}

func MustParse{{.Type}}(input any) *{{.Type}} {
	val, err := Parse{{.Type}}(input)
	if err != nil {
		panic(err)
	}
	return val
}

`))

type TemplateData struct {
	Package string
	Import  []string
	Type    string
}

func main() {
	if len(os.Args) != 4 {
		log.Fatalf("Usage: %s <package> <type> <output-file>", os.Args[0])
	}

	pkg, typ, out := os.Args[1], os.Args[2], os.Args[3]
	if err := run(pkg, typ, out); err != nil {
		log.Fatal(err)
	}

	p, _ := os.Getwd()
	fmt.Printf("%s generated successfully in %s\n", typ, filepath.Join(p, out))
}

func run(pkg, typ, outFile string) error {
	data := TemplateData{
		Package: pkg,
		Import:  []string{"database/sql/driver", "fmt", "strconv", "github.com/google/uuid"},
		Type:    typ,
	}

	f, err := os.Create(outFile)
	if err != nil {
		return fmt.Errorf("failed to create file: %w", err)
	}
	defer f.Close()

	if err := temp.Execute(f, data); err != nil {
		return fmt.Errorf("template execution failed: %w", err)
	}

	return nil
}