package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"text/template"
)

const header = "// Code generated by type-generator-tool. DO NOT EDIT.\n"

var temp = template.Must(
	template.New("typegen").Parse(
		header + `
package {{.Package}}

import (
	{{- range .Import}}
	"{{.}}"
	{{- end}}
)

type {{.Type}} struct {
	value any	
}

var {{.Type}}Nil = {{.Type}}{value: nil}

// Type returns the type name as string for Entgo compatibility
func ({{.Type}}) Type() string {
	return "{{.Type}}"
}

func New{{.Type}}() *{{.Type}} {
	return &{{.Type}}{}
}

func (c *{{.Type}}) MarshalText() ([]byte, error) {
	if strValue, ok := c.value.(string); ok {
		return []byte(strValue), nil
	}
	return nil, fmt.Errorf("invalid type for {{.Type}}: %T", c.value)
}

func (c *{{.Type}}) IsZero() bool {
	return c.value == nil
}

func (c *{{.Type}}) UnmarshalText(text []byte) error {
	c.value = string(text)
	return nil
}

func (c *{{.Type}}) Value() (driver.Value, error) {
	switch v := c.value.(type) {
	case nil:
		*c = {{.Type}}Nil
        return uuid.Nil.String(), nil
	case uuid.UUID:
		return v.String(), nil
	case string:
		return v, nil
	case []byte:
		if len(v) == 0 {
			return uuid.Nil.String(), nil
		}
		return string(v), nil
	case int:
		return strconv.Itoa(v), nil
	default:
		return nil, fmt.Errorf("unsupported type: %s", v)
	}
}

func (c *{{.Type}}) Scan(value any) error {
	switch v := value.(type) {
	case nil:
		*c = {{.Type}}Nil
        return nil
	case string:
		val, err := uuid.Parse(v)
		if err != nil {
			*c = {{.Type}}{value: v}
		}
		*c = {{.Type}}{value: val}
		return nil
	case []byte:
		*c = {{.Type}}{value: v}
		return nil
	case int:
		*c = {{.Type}}{value: strconv.Itoa(v)}
		return nil
	default:
		return fmt.Errorf("unsupported type: %T", v)
	}
}

func (c *{{.Type}}) Validate() error {
	if c.IsZero() {
		return fmt.Errorf("{{.Type}} is zero value")
	}

	switch v := c.value.(type) {
	case uuid.UUID:
		return nil 
	case string:
		if _, err := uuid.Parse(v); err != nil {
			return fmt.Errorf("invalid string format for {{.Type}}: %s", v)
		}
		return nil
	case []byte:
		strValue := string(v)
		if _, err := uuid.Parse(strValue); err != nil {
			return fmt.Errorf("invalid byte format for {{.Type}}: %s", strValue)
		}
		return nil
	case int:
		return fmt.Errorf("int type is not valid for {{.Type}}")
	default:
		return fmt.Errorf("unsupported type: %T", v)
	}
}

func (c *{{.Type}}) String() string {
	switch v := c.value.(type) {
	case uuid.UUID:
		return v.String() 
	case string:
		return v
	case []byte:
		if len(v) == 0 {
			return uuid.Nil.String()
		}
		return string(v)
	case int:
		return strconv.Itoa(v)
	default:
		return uuid.Nil.String()
	}
}

func (c *{{.Type}}) Matches(x interface{}) bool {
	switch v := x.(type) {
	case string:
		return c.value == v
	case []byte:
		return c.value == string(v)
	case int:
		if intValue, ok := c.value.(int); ok {
			return intValue == v
		}
		return false
	default:
		return false
	}
}

func Parse[T any](input any) (*{{.Type}}, error) {
	if input == "" {
		return &{{.Type}}{}, fmt.Errorf("input cannot be empty")
	}
	return &{{.Type}}{value: input}, nil
}

func MustParse[T any](input any) *{{.Type}} {
	val, err := Parse[T](input)
	if err != nil {
		panic(err)
	}
	return val
}

`))

type TemplateData struct {
	Package string
	Import  []string
	Type    string
}

func main() {
	if len(os.Args) != 4 {
		log.Fatalf("invalid args count: %d", len(os.Args)-1)
	}

	pkg, t, out := os.Args[1], os.Args[2], os.Args[3]
	if err := run(pkg, t, out); err != nil {
		log.Fatal(err)
	}

	p, _ := os.Getwd()
	fmt.Printf("%v generated\n", filepath.Join(p, out))
}

func run(pkg string, t string, outFile string) error {
	data := TemplateData{
		Package: pkg,
		Import:  []string{"database/sql/driver", "fmt", "strconv", "github.com/google/uuid"},
		Type:    t,
	}

	f, err := os.Create(outFile)
	if err != nil {
		return err
	}
	defer f.Close()

	return temp.Execute(f, data)
}