// Code generated by options-gen. DO NOT EDIT.

package getfreehandsbtnavailability

type OptOptionsSetter func(o *Options)

func NewOptions(
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithManagerLoadService(opt managerLoadService) OptOptionsSetter {
	return func(o *Options) {
		o.managerLoadService = opt

	}
}

func WithManagerPool(opt managerPool) OptOptionsSetter {
	return func(o *Options) {
		o.managerPool = opt

	}
}

func (o *Options) Validate() error {
	return nil
}
