// Code generated by options-gen. DO NOT EDIT.

package wshandshake

import (
	websocketstream "github.com/dndev-xx/go-ninja-chat/internal/websocket-stream"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithHttpUpgrade(opt *websocketstream.HTTPHandler) OptOptionsSetter {
	return func(o *Options) {
		o.httpUpgrade = opt

	}
}

func (o *Options) Validate() error {
	return nil
}
