// Code generated by options-gen v0.54.0. DO NOT EDIT.

package getfreehands

type OptOptionsSetter func(o *Options)

func NewOptions(
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithManagerPool(opt managerPool) OptOptionsSetter {
	return func(o *Options) { o.managerPool = opt }
}

func (o *Options) Validate() error {
	return nil
}
