// Code generated by options-gen v0.54.0. DO NOT EDIT.

package sendclientmessagejob

type OptOptionsSetter func(o *Options)

func NewOptions(
	messageProducer messageProducer,
	messageRepo messageRepository,
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	o.messageProducer = messageProducer
	o.messageRepo = messageRepo

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	return nil
}
