// Package pkg provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package pkg

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RVTW/jOAz9KwJ3j3acopfCt227hx66u9h0MIciB1lmYrXWx0h00iDwfx9QdvONQVFM",
	"T1IkkXx87zHegnLGO4uWIpRbiKpBI9P2Vkb8e4WW+IcPzmMgjekK+fih5u3CBSMJSug6XUMGtPEIJUQK",
	"2i4hg7d86fLxkJc4STkf7g/vcm28C0MhSQ2UsNTUdNVEOVPUtsZV/vZWLF1utX2RuWokFdoSBivbImWF",
	"vs8GWE+p1vYESJ+BwRjlEj8L+3EM/wrgAX90GD/N6P9j+O+HNmLTAWsonw8Inu9wueoFFTHBO7PUOqqg",
	"jbaSXOADI71n8LwdaJyhpfE9/FHsPViMBiweT9/12bsJN/9Iw5X3aPoMnMV/F1A+b+HPgIuPZ533GZyd",
	"lluQbfuBfPsZ6bPTIZEdNS58VtNvEcOXeK1y9SaJhCySJ+0slPDUoFDOEloSbiGoQTEqNTmD22egAkrC",
	"+i+6kEkbjCSNF+sG7WEmsZZRjJGcdUdKLQlz0gYvlToaarSdYSOeuWh+IVLHGYaVVngO8sHWWknCKPRR",
	"s0JHIUUcwi4wUDnXorRwOhg7rUd+Dxk6BHI+NvM0ZNouXPrT0tTy7a20r2LWeRZc3DWSxF2rWZvUbYQM",
	"Vhji0MvqKvnfo5VeQwnXk+nkGrJkkmTEYp2WJSa12KKSaWBnwqyrmJcKd4kDRu9sHDx8Nb3iZXRGcrX3",
	"LVOnnS1eIgN4/2jw7lezMs4Jt3ssxmytSTXaLsV/wZFTro0iF9+xmjn1isS+tKj4sWBnVa2ODdZJg9gZ",
	"I8MGStg/R1t7py2JhQsCh7ZSVZYVQ0xDfYzgHlfYOm+Y4eEVZNCFFkpYx7IoWqdk27hI5c30Zsqi/QwA",
	"AP//CABTHDgHAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
