// Code generated by options-gen. DO NOT EDIT.

package keycloakclient

type OptOptionsSetter func(o *Options)

func NewOptions(
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithBasePath(opt string) OptOptionsSetter {
	return func(o *Options) {
		o.basePath = opt

	}
}

func WithDebugMode(opt bool) OptOptionsSetter {
	return func(o *Options) {
		o.debugMode = opt

	}
}

func WithRealm(opt string) OptOptionsSetter {
	return func(o *Options) {
		o.realm = opt

	}
}

func WithClientID(opt string) OptOptionsSetter {
	return func(o *Options) {
		o.clientID = opt

	}
}

func WithClientSecret(opt string) OptOptionsSetter {
	return func(o *Options) {
		o.clientSecret = opt

	}
}

func (o *Options) Validate() error {
	return nil
}
