// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source=usecase.go -destination=mocks/usecase_mocks.gen.go -package=managerv1mocks
//

// Package managerv1mocks is a generated GoMock package.
package managerv1mocks

import (
	context "context"
	reflect "reflect"

	types "github.com/dndev-xx/go-ninja-chat/internal/types"
	gomock "go.uber.org/mock/gomock"
)

// MockmanagerPool is a mock of managerPool interface.
type MockmanagerPool struct {
	ctrl     *gomock.Controller
	recorder *MockmanagerPoolMockRecorder
	isgomock struct{}
}

// MockmanagerPoolMockRecorder is the mock recorder for MockmanagerPool.
type MockmanagerPoolMockRecorder struct {
	mock *MockmanagerPool
}

// NewMockmanagerPool creates a new mock instance.
func NewMockmanagerPool(ctrl *gomock.Controller) *MockmanagerPool {
	mock := &MockmanagerPool{ctrl: ctrl}
	mock.recorder = &MockmanagerPoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmanagerPool) EXPECT() *MockmanagerPoolMockRecorder {
	return m.recorder
}

// Put mocks base method.
func (m *MockmanagerPool) Put(ctx context.Context, managerID types.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, managerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockmanagerPoolMockRecorder) Put(ctx, managerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockmanagerPool)(nil).Put), ctx, managerID)
}
