// Package pkg provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.2.0 DO NOT EDIT.
package pkg

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RUUW/bRgz+KwS3hw2QLWXpgELAHpJmXbxhWNAEWIEsD5RES9ee7tQ7nhsj0H8f7qTY",
	"yey1exiGAX0ydCb5kR8/fg9Y236who14LB9wIEc9C7v09fYNfwjsZXVxydSwi2/KYInd9JmhoZ6xxLeL",
	"OXKxusAMHX8IynGDpbjAGfq6455i9tq6ngRLDEE1mKFsh5jvxSnTYob3i9YuVD9YJ1M70mGJrZIuVMva",
	"9nljGt4s7u/z1i6MMu9oUXckuTLCzpDOY0GP41xpLp8el7thcBzHx6bSnD86Z9Nwg7MDO1GcnmvbcPz9",
	"2vEaS/wq33OVz9l5Sn0VA8cMGxZSOuU+H2zMsGfvqeUj/41PCbvdBWYT/t2Y4R6kfMCGfe3UIMrGTdTW",
	"CCnj4fLm5go4BkLM80CmAT9wrdaqhip4Zdh70LZV9bO4b6Rj0OQF+uAFKoY/QlGc8g9wUhTFt0vMsFdG",
	"9aHH8kVR7HYWKW/ZxdleO+ZLMo1/w36wxvMhlw1JEoAJWlOleZLGX2dPUXHin1h2Rc/FnG1IaaqUVrL9",
	"PAZN0foIXREU1BrizFUQsQaUh11CBmvSnsFKx+6j8rzca7SyVjOZSTxHmo6S4jo4JdvrKI6pp4rJsTsL",
	"UcePX68fj+Dn329wFmJCSP/uETuRYYJTZm2TcpTEqfCczHu4DkO8E3jVkcCvZKhlB2dXK8xww85PA29O",
	"4oLswIYGhSWeLovlKWbpslKD+fqR50So9XLI2jWbBnjDRkAimKctUGWDQD/DOqZmC0LvGQZnK819ZC4u",
	"h2KNVYMlXlm/X2pqYe81t8evbB+SH3jReBfXMGkh9f5dUUxXa4RNmoKGQas6dZC/83GUhyde9KmzPlR0",
	"2sNzWn77JXL74l+EnYzoCNQ5NTATEDG//y8wV7OnwjW7DTvYBY4Z5u3fH+hndGT4I8weB2LTJUYLP66X",
	"T/jA/1xB/8TBJi6/QAE98cq0uacueXsX9+JTyrTX51UveMPaDn10oykKMwxOz4ZZ5rm2NenOeilfFi9P",
	"8miBd+OfAQAA//9WujeI6ggAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
