// Package pkg provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package pkg

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xUW2vcOhD+K2LOeTgHvGunSSEY+pBL02whELKBBtJ9mLVnbaW2pEijTcLi/14kO3sh",
	"29CH0icjeUYz32VmBYVujVak2EG+AoMWW2Ky8XR3Q4+eHE/OLwlLsuFOKsih7o8JKGwJcrgbDZGjyTkk",
	"YOnRS0sl5Gw9JeCKmloM2QttW2TIwXtZQgL8YkK+YytVBQk8jyo9kq3Rlvt2uIYcKsm1n48L3aalKmk5",
	"en5OKz1SUj3gqKiRU6mYrMImDQ866IaXhufj5XgNBrque20q4vxsrY7gjNWGLEuK14UuKXz/tbSAHP5J",
	"N1ylQ3YaU89CYJdASYyyibm7wLoEWnIOK9rzr9sm7H4dmPT1Z10CmyL5CkpyhZWGpQ5KFFoxSuXE5e3t",
	"taAQKEKeE6hK4QwVciELMfdOKnJONLqSxU7cf1yTaNCxaL1jMSfx3WfZIX0SB1mW/T+GBFqpZOtbyI+y",
	"bK1ZoLwiG7B9Ib6wRJeoSnfK6mSJssG5bCS/3JAzWjl6y26JHC2BfXSzB1xwj5ALETqce2athHRinZCI",
	"BTaOhOaa7JN0NN44aq51Q6h6qbfpjWVn0QBUeCv5ZRqk7HuaE1qyJz647vV08WrZr99uYbBNrBD/birW",
	"zKYvJ9VCR50lB1RwiuqHmHoTXC3OamRxhQorsuLkegIJLMm6HvDyINCpDSk0EnI4HGfjQ0jiHMQG0+rX",
	"VEeKteO3PE5JlULRkxi8JVhHTsPoBM6CLBhiJyXkcK0dv6NobGezJe73z8cmJH2zRbpZkKT3RUT1Icv6",
	"eVNMKvaPxjSyiD2lDy6AWG1tkfcG8ne8GFXapehqYKawhEzlOOhw9Afb6lfMnsKnWIqBoFDz49+oORm2",
	"pZiSXZIV68DtsYjSbg/E/SwI52JKL/zuq+e0pEablhSLPgoS8LYZZiNP00YX2NTacX6cHR+kwe2z7mcA",
	"AAD//9TVTfiDBgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
