// Code generated by MockGen. DO NOT EDIT.
// Source: handlers.go

// Package clientv1mocks is a generated GoMock package.
package clientv1mocks

import (
	context "context"
	reflect "reflect"

	gethistory "github.com/dndev-xx/go-ninja-chat/internal/usecase/client/get-history"
	sendmessage "github.com/dndev-xx/go-ninja-chat/internal/usecase/client/send-message"
	gomock "github.com/golang/mock/gomock"
	echo "github.com/labstack/echo/v4"
)

// MockgetHistoryUseCase is a mock of getHistoryUseCase interface.
type MockgetHistoryUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockgetHistoryUseCaseMockRecorder
}

// MockgetHistoryUseCaseMockRecorder is the mock recorder for MockgetHistoryUseCase.
type MockgetHistoryUseCaseMockRecorder struct {
	mock *MockgetHistoryUseCase
}

// NewMockgetHistoryUseCase creates a new mock instance.
func NewMockgetHistoryUseCase(ctrl *gomock.Controller) *MockgetHistoryUseCase {
	mock := &MockgetHistoryUseCase{ctrl: ctrl}
	mock.recorder = &MockgetHistoryUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgetHistoryUseCase) EXPECT() *MockgetHistoryUseCaseMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockgetHistoryUseCase) Handle(ctx context.Context, req gethistory.Request) (gethistory.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, req)
	ret0, _ := ret[0].(gethistory.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockgetHistoryUseCaseMockRecorder) Handle(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockgetHistoryUseCase)(nil).Handle), ctx, req)
}

// MocksendMsgUseCase is a mock of sendMsgUseCase interface.
type MocksendMsgUseCase struct {
	ctrl     *gomock.Controller
	recorder *MocksendMsgUseCaseMockRecorder
}

// MocksendMsgUseCaseMockRecorder is the mock recorder for MocksendMsgUseCase.
type MocksendMsgUseCaseMockRecorder struct {
	mock *MocksendMsgUseCase
}

// NewMocksendMsgUseCase creates a new mock instance.
func NewMocksendMsgUseCase(ctrl *gomock.Controller) *MocksendMsgUseCase {
	mock := &MocksendMsgUseCase{ctrl: ctrl}
	mock.recorder = &MocksendMsgUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksendMsgUseCase) EXPECT() *MocksendMsgUseCaseMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MocksendMsgUseCase) Handle(ctx context.Context, req sendmessage.Request) (sendmessage.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, req)
	ret0, _ := ret[0].(sendmessage.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MocksendMsgUseCaseMockRecorder) Handle(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MocksendMsgUseCase)(nil).Handle), ctx, req)
}

// MockwsUpdateHttpReqUseCase is a mock of wsUpdateHttpReqUseCase interface.
type MockwsUpdateHttpReqUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockwsUpdateHttpReqUseCaseMockRecorder
}

// MockwsUpdateHttpReqUseCaseMockRecorder is the mock recorder for MockwsUpdateHttpReqUseCase.
type MockwsUpdateHttpReqUseCaseMockRecorder struct {
	mock *MockwsUpdateHttpReqUseCase
}

// NewMockwsUpdateHttpReqUseCase creates a new mock instance.
func NewMockwsUpdateHttpReqUseCase(ctrl *gomock.Controller) *MockwsUpdateHttpReqUseCase {
	mock := &MockwsUpdateHttpReqUseCase{ctrl: ctrl}
	mock.recorder = &MockwsUpdateHttpReqUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockwsUpdateHttpReqUseCase) EXPECT() *MockwsUpdateHttpReqUseCaseMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockwsUpdateHttpReqUseCase) Handle(ctx echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockwsUpdateHttpReqUseCaseMockRecorder) Handle(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockwsUpdateHttpReqUseCase)(nil).Handle), ctx)
}
