// Code generated by MockGen. DO NOT EDIT.
// Source: handlers.go

// Package clientv1mocks is a generated GoMock package.
package clientv1mocks

import (
	context "context"
	reflect "reflect"

	getfreehandsbtnavailability "github.com/dndev-xx/go-ninja-chat/internal/usecase/manager/getFreeHandsBtnAvailability"
	gomock "github.com/golang/mock/gomock"
)

// MockgetFreeHandsBtnAvailabilityUseCase is a mock of getFreeHandsBtnAvailabilityUseCase interface.
type MockgetFreeHandsBtnAvailabilityUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockgetFreeHandsBtnAvailabilityUseCaseMockRecorder
}

// MockgetFreeHandsBtnAvailabilityUseCaseMockRecorder is the mock recorder for MockgetFreeHandsBtnAvailabilityUseCase.
type MockgetFreeHandsBtnAvailabilityUseCaseMockRecorder struct {
	mock *MockgetFreeHandsBtnAvailabilityUseCase
}

// NewMockgetFreeHandsBtnAvailabilityUseCase creates a new mock instance.
func NewMockgetFreeHandsBtnAvailabilityUseCase(ctrl *gomock.Controller) *MockgetFreeHandsBtnAvailabilityUseCase {
	mock := &MockgetFreeHandsBtnAvailabilityUseCase{ctrl: ctrl}
	mock.recorder = &MockgetFreeHandsBtnAvailabilityUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgetFreeHandsBtnAvailabilityUseCase) EXPECT() *MockgetFreeHandsBtnAvailabilityUseCaseMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockgetFreeHandsBtnAvailabilityUseCase) Handle(ctx context.Context, req getfreehandsbtnavailability.Request) (getfreehandsbtnavailability.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, req)
	ret0, _ := ret[0].(getfreehandsbtnavailability.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockgetFreeHandsBtnAvailabilityUseCaseMockRecorder) Handle(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockgetFreeHandsBtnAvailabilityUseCase)(nil).Handle), ctx, req)
}
